export const categories = [
  { id: 1, name: "Pizza", image: require("../assets/images/pizzaIcon.png") },
  { id: 2, name: "Burger", image: require("../assets/images/pizzaIcon.png") },
  { id: 3, name: "Italian", image: require("../assets/images/pizzaIcon.png") },
  { id: 4, name: "Chinese", image: require("../assets/images/pizzaIcon.png") },
  { id: 5, name: "Noodles", image: require("../assets/images/pizzaIcon.png") },
  { id: 6, name: "Sweets", image: require("../assets/images/pizzaIcon.png") },
];

export const features = {
  id: 1,
  title: "Hot and spicy",
  description: "soft and tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Papa Johns",
      image: require("../assets/images/pizzaRestaurant.jpg"),
      description: "Hot and spicy pizzas",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheesy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaItem.jpg"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheesy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaItem.jpg"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheesy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaItem.jpg"),
        },
      ],
    },
    {
      id: 2,
      name: "Papa Johns",
      image: require("../assets/images/pizzaRestaurant.jpg"),
      description: "Hot and spicy pizzas",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheesy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaItem.jpg"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheesy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaItem.jpg"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheesy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaItem.jpg"),
        },
      ],
    },
    {
      id: 3,
      name: "Papa Johns",
      image: require("../assets/images/pizzaRestaurant.jpg"),
      description: "Hot and spicy pizzas",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheesy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaItem.jpg"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheesy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaItem.jpg"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheesy garlic pizza",
          price: 10,
          image: require("../assets/images/pizzaItem.jpg"),
        },
      ],
    },
  ],
};
